language: python

python: 
	- "3.6"
#matrix:
# include:
#	 - os: linux
#	   python: 3.6
#	 - os: linux
#	   python: 3.7
#	 - os: linux
#	   python: 3.8
#	 - os: osx
#	   python: 3.8


	  #before_install:
	  #  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
	  #  - 	sudo apt-get -y install pandoc

install: 	  
  - pip install -r requirements-dev.txt

script:
  - coverage erase
  - coverage run -a --source ./sksurgerycalibration -m pytest -v -s ./tests/
  - coverage report -m
  - pylint --rcfile=tests/pylintrc sksurgerycalibration 
  - cd doc
  - sphinx-build -M html . build
